export function createStream(options: any): any;
export function detect(input: any): any;
export const eol: string;
export function fetch(input: any, sep: any, quo: any): any;
export function forEach(input: any, sep: any, quo: any, callback: any, ...args: any[]): void;
export function parse(input: any, sep: any, quo: any): any;
export function read(input: any, sep: any, quo: any, callback: any, ...args: any[]): any;
export function readAll(input: any, sep: any, quo: any, callback: any, ...args: any[]): any;
export function readChunk(input: any, sep: any, quo: any, callback: any, ...args: any[]): any;
export const separator: string;
export function stringify(input: any, sep: any): any;
